### ISSUE TITLE
Every reference to InventoryConfig points to the same file

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guide-microprofile-config#105]
The guide references InventoryConfig.java several times, first telling the user to create it, then to replace it to add dynamic config, then to replace it again, adding the Email.

However, in each case, the code displayed is the same, and it's the final code with all the features added.

This is not only confusing as it conflicts with the text, but also means that the user gets lots of errors in the file as it references things which are only created later on in the guide.

**Comment by yeekangc** [comment]
This looks to be an effect of converting the guide to newer format without adequate consideration to how it would affect the content/learning experience and the needed changes there.

**Comment by DannyS03** [comment]
Seems like tags in the `README.adoc` don't appropriately hide the necessary tags as the `InventoryConfig.java` class builds up to it's final form.

**Comment by Azquelt** [comment]
Looks good, thanks :+1:
