### ISSUE TITLE
Service files render incorrectly on the guide website which breaks application

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guide-microprofile-config#106]
On the guide website, the two service declaration files render with an additional `[]` at the end which is invalid and causes the app to break if the guide is followed.

org.eclipse.microprofile.config.spi.ConfigSource renders as
```
io.openliberty.guides.config.CustomConfigSource
[]
```

org.eclipse.microprofile.config.spi.Converter renders as
```
io.openliberty.guides.config.CustomEmailConverter
[]
```

If these extra characters are not removed, the tests fail and the app cannot be started.

**Comment by DannyS03** [comment]
- Work around is removing the hotspot tags (as there is only one line in the file) since the comment syntax implemented is not recognized 
- needs an end-to-end test

**Comment by yeekangc** [comment]
We need to fix these properly without affecting the learning quality and experience of the guide.

**Comment by DannyS03** [comment]
- Guide should work as desired now.
- As mentioned, need to properly fix implementation without affecting the learning quality and experience of the guide: will be looked into.

**Comment by Azquelt** [comment]
Looks good now, thanks :+1:
