### ISSUE TITLE
Update the Ordering multiple configuration sources section

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-config#134]
Starting mpConfig-1.3, server.xml is one of the configuration sources. See 
- https://aguibert.github.io/openliberty-cheat-sheet/#_microprofile_config
- https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_appconfig_validsources.html

**Comment by ankitagrawa** [comment]
- ID review completed.
- Need to merge code into qa branch.
