### ISSUE TITLE
Getting Started section contains urls to access the micro services

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/guide-microprofile-config#5]
The Getting Started part of the guide includes the cloning instruction + the three urls to access the micro services. Since the instructions to build and start the application appear later in the guide, it is confusing to see the urls in the Getting Started section. Should the urls be taken out there?

**Comment by yeekangc** [comment]
Yes, we need to clarity and address these.  At the minimum, we need to describe what the URLs (and hence, services) are and they are provided as starting point.  Obviously, should have these at the right spot(s) in the guide.

**Comment by JunyiSun** [comment]
The two URLs are moved to what you'll learn section with proper descriptions, @lavenal agrees on the changes, so this issue can be closed.
