### ISSUE TITLE
config ordinal is not strictly dynamic

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/guide-microprofile-config#58]
In https://openliberty.io/guides/microprofile-config.html#building-and-running-the-application it says
```
At first, the config_ordinal value of the custom configuration source is set to 50. A value of 50 does not override configuration values of the default microprofile-config.properties source, which has a config_ordinal value of 100.

However, you can manually change the config_ordinal value to a larger number in the resources/CustomConfigSource.json file.

Your changes are added dynamically, and you do not need to restart the server. Refresh http://localhost:9080/config to see the dynamic changes.
```

However, the ordinal of a config source is not truely dynamic... once the Config instance is created then the order of the ConfigSources is fixed. In the example used by the guide, the bean is RequestScoped and, in our current implementation, that results in a new Config instance per request, thus making it appear to be dynamic. However, that implementation could change in future versions and so the guide should probably avoid suggesting that the ordinal is dynamic.

**Comment by yeekangc** [comment]
@JunyiSun, we should update the guide to accurately reflect how mpConfig works i.e. not indicate that the ordinal is dynamic.  When it doubt, please reach out to Tom.

**Comment by tevans78** [comment]
@Emily-Jiang ^^^^
