### ISSUE TITLE
portNumber in the guide does not work

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/guide-microprofile-config#6]
When starting the defaultServer, the following warning appeared:

[WARNING ] CWNEN0057W: The io.openliberty.guides.microprofile.InventoryConfig.portNumber injection target must not be declared static.

The getPortNumber method returns 0 instead of 9080.

**Comment by JunyiSun** [comment]
@lavenal Hi Lavena, you can check out the latest code, the issue has been fixed. Thank you for pointing it out.

**Comment by JunyiSun** [comment]
Lavena agrees to close this issue. Thank you.
