### ISSUE TITLE
ConfigurationTest test case fails on Linux environment

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-microprofile-config#78]
The MP Config test case has a real bug. The problem is the order of the test cases being run on different platforms, Mac vs Linux. When the InventoryEndpointTest is run before the ConfigurationTest where there are two checks to verify the number of systems in the inventory, the test will fail. On the Mac OS, where most people run their guides, the usual test order has not reveal this bug. 

Usual test order: 
Mac: - PASSED
1. ConfigurationTest - PASSED
2. SystenEndpointTest - PASSED
3. InventoryEndpointTest - PASSED
	
Linux: - FAILED
1. SystemEndpointTest - PASSED
2. InventoryEndpointTest - PASSED
3. ConfigurationTest - FAILED

Set runOrder = alphabetical - TO PASS THE TEST SUITES
1. Con
2. Inv
3. Sys

Set runOrder = reversealphabatical - TO REPRODUCE FAILURE ON MAC
Reason: no delete or clear cache method in inventory service and test

Note: Add `<runOrder>reversealphabetical</runOrder>` under `maven-failsafe-plugin`

Solution options: 
1. Use the `runOrder` to set the order to run the test cases
Cons: not a solid long term solution.

2. Fix the logic in the config test case
Cons: may need to introduce the delete mechanism in the inventory service that's not needed for the guide.

**Comment by evelinec** [comment]
This issue may impact the upcoming conference. Assign to @proubatsis to take a look.

**Comment by proubatsis** [comment]
@evelinec I don't see any reason that `ConfigurationTest.java` needs to make the assertions that the inventory is empty as that functionality is not the point of this test. That is being covered in `InventoryTest.java`. So instead of making them run in a particular order, would removing these assertions be a viable solution?

**Comment by evelinec** [comment]
Tested on a Linux environment. The fix is good.
