### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-microprofile-config#81]
### Checklist for Post-Review
**Through the browser:**
- [x] Read through guide, making sure that the flow of the guide is good
- [x] Click all links to make sure they lead to the correct place
- [x] Make sure hotspots, code_commands and files are correct
- [x] Run Acrolinx

**Comment by ismartspace** [comment]
### Checklist for Review
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present
- [ ] Any links are hyperlinks with the webpage title not the URL
- [ ] Feature versions should not be included in the guide
**In the README.adoc:**
- [ ] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
    - [ ] start directory
    - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by ismartspace** [comment]
- [ ] maven-liberty-plugin version not removed in pom.xml

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
