### ISSUE TITLE
multipane issues

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-config#84]
- Injecting static configuration
   - [x] the hotspot for the mpConfig not right
      - Look for the dependency with the `mpConfig` artifact ID
- Creating custom converters
  - [x] `Create the CustomEmailConverter class` highlighted the code
- Building and running the application
  - [x] The URL should not be monospaced
    - Refresh `http://localhost:9080/config` to see the dynamic changes.

**Comment by justineechen** [comment]
If it says ______ class, we can still highlight the class code, but when there is a file that is mentioned we switch tabs.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-microprofile-config/commit/7682d5bad9ef0756b843842806d6e76a5ee46ef3

**Comment by gkwan-ibm** [comment]
why "Create the Email Class." not highlight but "Create the CustomEmailConverter class" highligh the code `public ... { ...} `?

**Comment by justineechen** [comment]
I'm sorry, I misunderstood your initial point ^ I didn't see that it was Create/ in an action arrow! That shouldn't highlight anything.

**Comment by gkwan-ibm** [comment]
Reopen for the following:

- scroll until “Injecting dynamic configuration”
- you will see the Create and Replace commands can switch the files correctly
- then scroll down to Creating custom converters
- the commands cannot switch the files correctly
- also, when click on the commands, the file is not focused

**Comment by justineechen** [comment]
https://qa-guides-multipane.mybluemix.net/guides/microprofile-config.html#injecting-static-configuration

The files are focused now in Injecting dynamic configuration

**Comment by gkwan-ibm** [comment]
> Reopen for the following:
>     * scroll until “Injecting dynamic configuration”
>     * you will see the Create and Replace commands can switch the files correctly
>     * then scroll down to Creating custom converters
>     * the commands cannot switch the files correctly
>     * also, when click on the commands, the file is not focused
It was resolved.
