### ISSUE TITLE
[documentation][sample] io.openliberty.guides.inventory.InventoryResource 

### ISSUE THREAD

**Issue by rodede** [OpenLiberty/guide-microprofile-config#91]
we need to have a get() operation on inventoryConfig.isInMaintenance() test (line 46 and 69) in the **start** directory
```
        if (!inventoryConfig.isInMaintenance().get()) {
```

**Comment by justineechen** [comment]
@rodede 
`inventoryConfig.isInMaintenance()` is already a method that returns the boolean, would you explain why a get() operation is required in this case?

**Comment by rodede** [comment]
hey Justine - I tried to run the example @Voxxed Days Bucharest while encountered this tinny issue
If i remember correctly, in that particular case, the method returns a Provider<Boolean> (to deal with dynamic config), so i needed to call the get() to have the actual value (true or false).
Graham is aware about this (and I think in the "final" directory, we have the call to "get()" method)

I hope this clarifies - have fun!

**Comment by justineechen** [comment]
@rodede 
Hi Dan, 
Thank you for replying so quickly! So in the `InventoryConfig.java` file we have the `Provider<Boolean>` named `inMaintenance` and a separate method `isInMaintenance()` that calls `get()` on the `Provided<Boolean>` like so:

```
  public boolean isInMaintenance() {
    return inMaintenance.get();
  }
```
And in the `start` directory, we don't actually check for the system in maintenance until the user is asked to manually replace their `InventoryResource.java` file in the guide.

**Comment by rodede** [comment]
sorry, you're right: i think i let my IDE to generate the getter for that field and i didn't payed attention to the actual example code (where you call the `get()` method)

sorry again to waste your time - thank you !

**Comment by justineechen** [comment]
No worries! Thank you for giving us your feedback.
